In [1]:
#series is the object of pandas library and it represent 1D data structure

In [2]:
import pandas as pd
import numpy as np

In [5]:
#declaring the series
s = pd.Series([12,34,-87,3,-1])
s

0    12
1    34
2   -87
3     3
4    -1
dtype: int64

In [6]:
s = pd.Series([12,34,-87,3,-1],index = ['a','b','c','d','e'])
s

a    12
b    34
c   -87
d     3
e    -1
dtype: int64

In [9]:
#checking the values and index in series 
s.values
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [12]:
s[2]

C:\Users\sies\AppData\Local\Temp\ipykernel_18152\2635755408.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[2]


np.int64(-87)

In [13]:
s['a']

np.int64(12)

In [15]:
s[0:2] #slicing of series

a    12
b    34
dtype: int64

In [16]:
s[['b','d']]

b    34
d     3
dtype: int64

In [17]:
s[1]=3

C:\Users\sies\AppData\Local\Temp\ipykernel_18152\473058777.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  s[1]=3


In [19]:
s.values

array([ 12,   3, -87,   3,  -1])

In [20]:
#defining Series from numpy array and other series
arr = np.array([1,2,3,4])
s3 = pd.Series(arr)
s3

0    1
1    2
2    3
3    4
dtype: int64

In [21]:
s3[2]

np.int64(3)

In [22]:
arr[2]

np.int64(3)

In [23]:
arr[2] = 0
s3

0    1
1    2
2    0
3    4
dtype: int64

In [24]:
#filtering the values
s[s>2]

a    12
b     3
d     3
dtype: int64

In [27]:
#opertions and mathemtical functions
s/2
s*2
s+100

a    112
b    103
c     13
d    103
e     99
dtype: int64

In [28]:
np.log(s)

C:\Users\sies\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)


a    2.484907
b    1.098612
c         NaN
d    1.098612
e         NaN
dtype: float64

In [29]:
#evaluating Values
eva = pd.Series([0,1,1,2,10],index=['abc','xyz','xyz','mno','def'])
eva

abc     0
xyz     1
xyz     1
mno     2
def    10
dtype: int64

In [30]:
eva.unique()

array([ 0,  1,  2, 10])

In [31]:
test=eva.unique()
test

array([ 0,  1,  2, 10])

In [33]:
eva.value_counts()

1     2
0     1
2     1
10    1
Name: count, dtype: int64

In [35]:
eva.isna()

abc    False
xyz    False
xyz    False
mno    False
def    False
dtype: bool

In [36]:
#NaN Values #Nan (not a number)
s2 = pd.Series([5,-3,np.nan,14])
s2

0     5.0
1    -3.0
2     NaN
3    14.0
dtype: float64

In [37]:
s2.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [38]:
s2.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [39]:
s2.notnull()

0     True
1     True
2    False
3     True
dtype: bool

In [40]:
s2[s2.notnull()]

0     5.0
1    -3.0
3    14.0
dtype: float64

In [41]:
#Series as dictionaries
mydict = {'red':2000,'blue':1000,'yellow':500,'orange':1000}
mydict

{'red': 2000, 'blue': 1000, 'yellow': 500, 'orange': 1000}

In [45]:
myseries=pd.Series(mydict)
myseries

red       2000
blue      1000
yellow     500
orange    1000
dtype: int64

In [48]:
colors = ['red','blue','yellow','orange']
myseries1=pd.Series(mydict,index=colors)
myseries1

red       2000
blue      1000
yellow     500
orange    1000
dtype: int64

In [49]:
myseries+myseries1

red       4000
blue      2000
yellow    1000
orange    2000
dtype: int64

In [50]:
 #defining pandas
data = {'color' :['blue','green','yellow','red','white'],
        'object' :['ball','pen','pencil','paper','mug'],
        'price' :[1.2,1.0,0.6,0.9,1.7]}
frame = pd.DataFrame(data)
frame

color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    0.6
3     red   paper    0.9
4   white     mug    1.7

In [51]:
frame2 = pd.DataFrame(data,index = ['one','two','three','four','five'])
frame2

color  object  price
one      blue    ball    1.2
two     green     pen    1.0
three  yellow  pencil    0.6
four      red   paper    0.9
five    white     mug    1.7

In [54]:
frame3 = pd.DataFrame(np.arange(16).reshape((4,4)),
                      index =['blue','green','yellow','red'],
        columns =['ball','pen','pencil','paper'])
frame3

ball  pen  pencil  paper
blue       0    1       2      3
green      4    5       6      7
yellow     8    9      10     11
red       12   13      14     15

In [56]:
frame3.columns

Index(['ball', 'pen', 'pencil', 'paper'], dtype='object')

In [57]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five'], dtype='object')

In [58]:
frame3.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])