In [1]:
import numpy as np

In [2]:
#types of data
g = np.array([['a','b'],['c','d']])
g

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [5]:
g.dtype

dtype('<U1')

In [6]:
g.dtype.name

'str32'

In [7]:
g.shape

(2, 2)

In [8]:
g.ndim

2

In [9]:
f = np.array([[1,2,3],[4,5,6]],dtype = complex)
f

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [12]:
#intrinsic Creation of array
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
#A feature thst will be particularly useful is arange()
#This function generates Numpy arrays with numerical sequences that
#respopnd to particular rules depending on the passed arguments.
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,12,3)
np.arange(0,12,3.5)

array([ 0. ,  3.5,  7. , 10.5])

In [19]:
np.random.random(3)

array([0.4917538 , 0.9040078 , 0.48411535])

In [20]:
np.random.random((3,3))

array([[0.55353017, 0.56387924, 0.52509298],
       [0.5564645 , 0.45239592, 0.41996573],
       [0.23215109, 0.83179263, 0.08673785]])

In [31]:
np.random.randn(4,4) #normal distribution

array([[ 1.57444133,  2.52496314, -1.82632467,  0.60922478],
       [-0.53545769, -0.18531888, -0.24293719, -1.63420952],
       [ 0.38902132, -0.08291107,  0.02154114,  0.0799727 ],
       [-0.87520359, -0.17400416,  0.73605541, -0.35077749]])

In [32]:
np.random.rand(3,3) #uniform distributions

array([[0.17192864, 0.10915811, 0.14133389],
       [0.81902272, 0.97652116, 0.35898004],
       [0.05178054, 0.11140627, 0.44732076]])

In [36]:
np.random.randint(4,20,100)

array([ 7, 19,  4, 18, 10, 11,  8,  9,  8, 17,  5, 11,  6,  7, 12,  6, 13,
       19,  5,  8,  7, 13,  8,  7,  9, 11, 11, 10, 17, 13,  6,  8, 19,  9,
       14,  4, 16,  6,  9, 17,  7, 11, 13,  7,  8, 15, 17, 15, 15, 16, 17,
       16, 10, 11, 12, 10,  4, 13, 12, 17, 17,  7,  7,  4, 14, 12,  9,  6,
        6, 18, 14, 15, 19, 18, 16,  4, 19,  5, 10, 13, 10, 15, 12,  5,  7,
        6, 16, 15,  7,  8, 19, 12,  9, 16,  6, 11, 13, 11, 13, 13],
      dtype=int32)

In [37]:
#Basic operations 

In [38]:
a = np.arange(4)

In [39]:
a

array([0, 1, 2, 3])

In [40]:
a+4

array([4, 5, 6, 7])

In [41]:
a*2

array([0, 2, 4, 6])

In [42]:
a//2

array([0, 0, 1, 1])

In [43]:
a/2

array([0. , 0.5, 1. , 1.5])

In [44]:
b = np.arange(4,8)

In [45]:
b

array([4, 5, 6, 7])

In [48]:
print(a+b)
print(a-b)
print(a*b)
print(a//b)
print(a/b)
print(a * np.sqrt(b))
print(a*np.sin(b))

[ 4  6  8 10]
[-4 -4 -4 -4]
[ 0  5 12 21]
[0 0 0 0]
[0.         0.2        0.33333333 0.42857143]
[0.         2.23606798 4.89897949 7.93725393]
[-0.         -0.95892427 -0.558831    1.9709598 ]


In [49]:
#multi-dimenstional case
a = np.arange(0,9).reshape(3,3)
print(a)
b = np.ones((3,3))
print(b)
print(a*b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [50]:
np.dot(a,b)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [51]:
a*b

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [52]:
np.dot(b,a)

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

In [54]:
#increment and decrement
a +=1
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [55]:
a -= 1
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
a *=2
a

array([[ 4,  8, 12],
       [16, 20, 24],
       [28, 32, 36]])

In [60]:
#universal functions like sqrt(),log(),sin()
d = np.arange(3,10)
d

array([3, 4, 5, 6, 7, 8, 9])

In [61]:
np.sqrt(d)

array([1.73205081, 2.        , 2.23606798, 2.44948974, 2.64575131,
       2.82842712, 3.        ])

In [62]:
np.log(d)

array([1.09861229, 1.38629436, 1.60943791, 1.79175947, 1.94591015,
       2.07944154, 2.19722458])

In [63]:
np.sin(d)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ,
        0.98935825,  0.41211849])