In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [ ]:
#Creating Arrays

In [41]:
import numpy as np
a = np.array([1,2,3])
print(a)
np.shape(a)
type(a)
a.dtype
a.ndim

[1 2 3]


1

In [23]:
a = np.array([1,2,3])
np.dtype[a]

numpy.dtype[array([1, 2, 3])]

In [30]:
b = np.array([(1.5,2,3),(4,5,6)],dtype=float)
b.shape
b.size
b.dtype

dtype('float64')

In [42]:
c = np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)],[(3,2,1),(4,5,6)]],dtype=float)
c.size
c.shape
c.ndim

3

In [45]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
np.ones((5,3,4),dtype = np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [51]:
d = np.arange(10,30,5.5)
#parameter(start,stop,step)
print(d)

[10.  15.5 21.  26.5]


In [55]:
print(np.linspace(0,2,17))
#parameter(start,stop,no. of values which we want)

[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
 1.5   1.625 1.75  1.875 2.   ]


In [58]:
print(np.full((2,2),7))

[[7 7]
 [7 7]]


In [59]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [63]:
print(np.random.random((2,2)))

[[0.015867   0.74220431]
 [0.35529139 0.1182028 ]]


In [68]:
print(np.empty((3,2)))

[[9.34577196e-307 9.34598246e-307]
 [1.60218491e-306 1.69119873e-306]
 [1.24611673e-306 1.00136897e-307]]
